# -*- coding: utf-8 -*-
# Batch 1: ids 1-117 (title, TOC, overview, process, deodorization table, crane)
PART = {
1: "2026",
2: "Pyrolysis Gasification Treatment of 5 Tons of High-Calorific-Value Waste",
3: "Project Proposal",
4: "Harmless Technical Treatment of High-Calorific-Value Waste in Bangladesh",
5: "(5 tons/day)",
6: "Design Proposal",
7: "Table of Contents",
8: "Chapter 1 Project Overview\t1",
9: "Chapter 2 Process and Technical Scheme\t1",
10: "Determination of the Waste Treatment Technology\t1",
11: "Process Scheme and Flow\t2",
12: "Waste Receiving System\t2",
13: "Plant Deodorization System\t2",
14: "Feeding and Conveying System\t3",
15: "High-Temperature Pyrolysis Gasification System\t4",
16: "Waste Heat Recovery System\t6",
17: "Flue Gas Purification System\t7",
18: "Three-Waste (Bottom Ash, Fly Ash, Leachate) Treatment System\t14",
19: "Central Control System\t15",
20: "Equipment List\t15",
21: "Treatment Performance\t17",
22: "Main Pollution Prevention and Control Measures and Mechanisms\t18",
23: "Dioxin Removal Process\t18",
24: "NOX Removal Process\t18",
25: "Deacidification Process\t19",
26: "Chapter 3 Engineering Design\t19",
27: "Principles of Overall Scheme Design\t19",
28: "General Layout\t20",
29: "Project Site Planning Concepts Based on Layout and Site Selection Principles\t20",
30: "Chapter 4 Project Implementation and Schedule\t23",
31: "Chapter 5 Operating Cost Estimation\t24",
32: "Chapter 6 Technical Features\t25",
33: "Key Technologies\t25",
34: "System Advantages\t26",
35: "Small Footprint\t26",
36: "Low Investment and Operating Cost\t27",
37: "Low Pollution Generation, Compliant Emissions without Secondary Pollution\t27",
38: "Fully Enclosed Operation with Automatic Control\t27",
39: "On-Site and Nearby Harmless Treatment\t27",
40: "Chapter 7 Reference Cases for Visits\t28",
41: "Case Photos\t34",
42: "Chapter 1 Project Overview",
43: "(1)",
44: "Project name: Bangladesh High-Calorific-Value Waste Harmless Treatment Project;",
45: "(2)",
46: "Designed daily processing capacity: 5 tons/day per set, with 1 project site to be established:",
47: "(3)",
48: "Equipment investment: RMB 8.6 million (ex-works price)",
49: "(4)",
50: "Project land area: 800m2",
51: "(5)",
52: "Waste conditions: waste with calorific value ≥900 kcal\tand moisture content ≤60%;",
53: "(6)",
54: "Energy required: (0# diesel or firewood) only for ignition and furnace curing; no additional fuel is required during normal operation;",
55: "(7)",
56: "Slag treatment: the bottom ash has met discharge standards and can be landfilled, used for road paving, or made into bricks at brick plants;",
57: "(8)",
58: "Service life: 15-20 years;",
59: "(9)",
60: "Flue gas emission targets: complying with the requirements of the Standard for Pollution Control on Municipal Solid Waste Incineration (GB18485-2014).",
61: "Process and Technical Scheme",
62: "Determination of the Waste Treatment Technology",
63: "The waste of this project is mainly industrial waste, such as packaging materials, with a moisture content of 5.7%, plastics 29%, paper 51%, foil/",
64: "composite materials 15%, others 5%, with a calorific value reaching 5400kcal/kg.",
65: "This type of industrial solid waste has a high unit calorific value, but the total amount of waste generated is small. The total chemical thermal power released by combustion is relatively limited. After heat exchange in the waste heat boiler, heat losses and thermodynamic cycle conversion, the maximum net output power of the system is only about 300 W, with a total daily power generation of 7.2kWh. Although the fuel itself has an excellent calorific value, the effective energy base available for power generation is very low. If a complete power generation set including waste heat boiler, steam turbine, generator and circulating water is equipped, the equipment investment, auxiliary energy consumption and O&M costs would far exceed the meager power generation revenue, and the overall energy conversion efficiency is low, with input exceeding output. Therefore, it is not recommended to install a power generation system in this project.",
66: "Considering that Bangladesh is located in a tropical monsoon climate zone where no heating is required in winter, if the waste heat of the plant has no other utilization value, it is discharged directly after heat exchange.",
67: "It is recommended to adopt a new treatment process combining high-temperature pyrolysis gasification with incineration, using a chain grate as the core component of incineration and enlarging the furnace cavity of the secondary combustion chamber to satisfy the flue gas residence time.",
68: "Process Scheme and Flow",
69: "The project process flow includes:",
70: "Waste Receiving → Conveying and Feeding System → High-Temperature Pyrolysis Gasification System → Waste Heat Recovery System → Flue Gas Purification System → Three-Waste (Bottom Ash, Fly Ash, Leachate) Treatment System → Central Control System",
71: "Waste Receiving System",
72: "Waste is transported to the incineration plant by waste trucks, weighed by the electronic truck scale, and then enters the tipping hall and is unloaded into the waste collection pit. The sufficient effective volume of the waste storage pit ensures the raw material supply of the pyrolysis furnace when the waste supply fluctuates severely, making the reaction in the furnace more stable.",
73: "Plant Deodorization System",
74: "It is composed of suction fans, spray deodorization system, etc., and adsorbs odor molecules in the air through deodorizer. The deodorizer quickly adsorbs odor molecules in the air through centrifugal atomization, and the microorganisms and enzymes it contains can decompose the adsorbed odorous substances in time.",
75: "Meanwhile, the highly active beneficial microbial flora contained in the deodorizer can inhibit the proliferation of spoilage microorganisms, thereby slowing down the generation of odorous gases. When the waste pyrolysis gasifier is in operation, the oxygen supply fan draws air from the waste storage pit to maintain the negative pressure state of the pit, with makeup air coming through the opening of the waste discharge doors. The biomass spray deodorization system is automatically started periodically to remove odor molecules in the room. With both schemes implemented simultaneously, odors can be well removed and odor escape prevented.",
76: "Odor Point",
77: "Location",
78: "Characteristics",
79: "Deodorization Measures",
80: "1",
81: "Plant roads",
82: "Dripping from waste trucks pollutes the road surface; deposited odorous gases exist",
83: "(Slight)",
84: "Water flushing;",
85: "Plant deodorizer spraying.",
86: "2",
87: "Waste tipping hall",
88: "(Severe)",
89: "Odor from the waste bunker escapes through the discharge doors",
90: "Enclosed structure with slightly negative pressure;",
91: "Air curtains at the gates prevent odorous gas from escaping;",
92: "Waste discharge doors are opened under the guidance of the central control room;",
93: "Water flushing and plant deodorizer spraying.",
94: "3",
95: "Waste pit",
96: "Odor from waste fermentation; main components: H2S, NH3, SO2, CH4 and mercaptan",
97: "During normal operation, primary air is drawn from the upper part of the waste pit, and the odorous gas is burned and decomposed in the incinerator;",
98: "When the incinerator is shut down, the odorous gas is drawn by the deodorizer",
99: "and discharged in compliance with standards after adsorption by the activated carbon device.",
100: "4",
101: "Leachate tank,",
102: "flushing corridor",
103: "Area where leachate drainage converges,",
104: "strong odor",
105: "Mechanical ventilation with fresh air drawn from outdoors",
106: "Mechanical exhaust, with exhaust air sent to the waste pit",
107: "5",
108: "Rear furnace area",
109: "(slag pit)",
110: "Odor of residual organic matter after incineration",
111: "High-level discharge",
112: "Exhaust drawn into the secondary air fan",
113: "6",
114: "Central control room and visitor corridor",
115: "Escape of odor from waste storage,",
116: "odorous gas pollution from incineration (Slight)",
117: "1. Effectively separated from odor sources, supplied with outdoor fresh air, and kept at positive pressure to prevent odor intrusion",
}
