# -*- coding: utf-8 -*-
# Batch 5: ids 382-443 (installation schedule, operating cost, technical features)
PART = {
382: "Timeline (Day **)",
383: "Equipment design and fabrication",
384: "1—60",
385: "Equipment shipment",
386: "61-67",
387: "Equipment installation",
388: "3.1",
389: "First installation of equipment",
390: "68-88",
391: "3.2",
392: "Second installation of equipment",
393: "89-96",
394: "Commissioning (training)",
395: "97-104",
396: "Furnace curing (training)",
397: "105-113",
398: "Trial operation (training)",
399: "113-120",
400: "Chapter 5  Operating Cost Estimation",
401: "The design scale of this project is 5t/d. The unit operating cost of the project includes electricity fees, chemical fees, staff wages and maintenance management costs, as well as the calculated operating cost per ton of waste. See the table below; the specific calculation process is as follows:",
402: "Electricity cost: the installed power is about 100kwh; some equipment runs continuously and some intermittently, converted into a daily consumption of 1080kw. The average industrial electricity price in Bangladesh is about 0.56 RMB/kWh, so the electricity cost is about 605 RMB/day.",
403: "Chemical fees: including caustic soda, urea, activated carbon, quicklime, deodorizing liquid, water, etc. Considering that prices are lower than in China, the total daily consumption is estimated at about 100 RMB.",
404: "Total plant workforce: 7 persons (calculated at the Bangladesh average wage of 800 RMB/month)",
405: "Position",
406: "Configuration",
407: "Shift system",
408: "Headcount",
409: "Mechanical and electrical maintenance worker",
410: "Central control room operation and monitoring",
411: "Chemical preparation, slag discharge and patrol inspection",
412: "Total",
413: "③ Staff wages: 7 persons at (800 RMB/(person·month)) *12/365 = 184 RMB/day.",
414: "Equipment maintenance cost: annual maintenance cost is 10,000 RMB, daily expenditure 27 RMB.",
415: "Solid waste treatment cost: the bottom ash of this project can be recycled for brick making, generating additional value, which is not calculated here.",
416: "Item",
417: "Operating cost (RMB/day)",
418: "Operating cost (RMB/ton)",
419: "Electricity fee",
420: "605",
421: "121",
422: "Chemical fees",
423: "100",
424: "20",
425: "Worker wages",
426: "184",
427: "36.8",
428: "Equipment maintenance cost",
429: "27",
430: "5.4",
431: "Total",
432: "916",
433: "181.2",
434: "Project Operating Cost Table",
435: "The above is only the estimated operating cost (the actual operating cost shall be adjusted according to the local labor, electricity price and environmental protection requirements, etc.).",
436: "Chapter 6 Technical Features",
437: "Key Technologies",
438: "The mechanical movement of the grate realizes the physical and chemical changes of the waste at each stage, promoting waste combustion",
439: "The waste in the furnace burns stably and relatively completely, with little fly ash and low loss on ignition",
440: "Material on the grate burns in layers and zones",
441: "After entering the furnace, the material gradually moves backward with the grate. In the front part of the grate is the preheating and drying zone of the new material; then the material begins to pyrolyze and gasify (i.e. the release of waste volatiles), then ignites and enters the combustion zone; in the middle and rear part is the coke combustion zone, where oxidation and reduction reactions proceed simultaneously, releasing a large amount of heat. At the tail of the grate is the ash burnout zone, where the remaining residual coke in the ash is continuously burned and completely burnt out.",
442: "Staged and controllable air supply on the grate",
443: "In the preheating and drying zone and the pyrolysis gasification zone (i.e. the release of waste volatiles), not much air is needed, while in the coke combustion zone sufficient air must be guaranteed to meet the oxygen required for combustion. To adapt to the different air volume requirements of each section of the grate combustion, the area under the grate is divided into several air chambers for staged air supply (primary air). Each air chamber is tightly sealed to prevent short circuits that would lose the regulating function. To make the air volume distribution uniform across the entire grate width, air is supplied from both sides. The air volume of each air chamber is regulated separately by an individual damper. The opening of each damper shall be determined through repeated operating tests according to the characteristics of different fuels to find the optimal opening position for material combustion. When the material characteristics change, it can be readjusted. This technology adopts staged air supply with adjustable air supply, avoiding the drawback of excess air at both the front and rear ends of the furnace and insufficient air in the middle, thereby achieving the best operating effect.",
}
