# -*- coding: utf-8 -*-
# Batch 4 (corrected): ids 297-381 (treatment performance table, pollution control, engineering design)
PART = {
297: "2.4 Treatment Performance",
298: "Flue gas treatment of this technology: semi-dry + dry deacidification. After high-temperature decomposition and three-stage cooling, the flue gas enters the bag filter for dust removal, the deacidification device removes acidic gases, and after activated carbon adsorption it is discharged in compliance with standards. The slag is mechanically squeezed by the grate and magnetically separated by the magnetic separator, and discharged out of the furnace periodically. The secondary pollutants in the application of this technology are mainly dioxins, nitrogen oxides, carbon monoxide, sulfur dioxide, hydrogen chloride, mercury and its compounds in the flue gas. Their main control measures, hazards and treatment effects are shown in the table below.",
299: "Secondary Pollution and Control Table (mg/m3)",
300: "Secondary Pollutant",
301: "Test Result",
302: "Hazard",
303: "Control Measures",
304: "Treatment Effect",
305: "Combined use of activated carbon adsorption, bag filter, etc.",
306: "Stable compliant discharge",
307: "Particulate matter",
308: "8.93",
309: "Process interception of particulate matter. The intercepted fly ash is",
310: "solidified and stabilized and disposed of as hazardous waste in accordance",
311: "direct",
312: "with hazardous waste management requirements.",
313: "Carbon monoxide",
314: "50",
315: "pollutes the atmosphere and indirectly affects",
316: "Control the secondary combustion chamber temperature and flue gas residence time to",
317: "thoroughly control its generation.",
318: "Nitrogen oxides",
319: "92",
320: "water and soil",
321: "Sulfur dioxide",
322: "ND",
323: "environments.",
324: "Semi-dry deacidification",
325: "Hydrogen chloride",
326: "1.22",
327: "Mercury and its compounds",
328: "Activated carbon adsorption + bag filter",
329: "Cadmium, thallium and their compounds",
330: "Antimony, arsenic, lead, chromium, cobalt, copper, manganese, nickel and",
331: "their compounds",
332: "0.05",
333: "Dioxins (ng",
334: "TEQ/m3)",
335: "0.0063",
336: "Carcinogenic",
337: "Thoroughly decompose it; flue gas quenching measures are adopted to prevent the secondary synthesis of dioxins.",
338: "Far below the national standard",
339: "2.5 Main Pollution Prevention and Control Measures and Mechanisms",
340: "2.5.1 Dioxin Removal Process",
341: "First, the temperature in the primary combustion chamber is controlled at 600℃ to 800℃, and the oxygen supply is controlled to maintain a reducing atmosphere, so that copper, aluminum and iron will not be oxidized, no CuO is produced, and no CuCl2 is generated or present — thus there is no catalyst for dioxin re-synthesis (CuO, CuCl2 and other compounds). Without the catalysis of CuCl2 and carbon atoms, the synthesis of dioxins becomes impossible.",
342: "Second, through 3T+E combustion control, the unburned gas containing dioxins is completely burned, suppressing dioxin generation to the lowest level.",
343: "Third, the heat exchanger and the semi-dry quench tower are used to quench the flue gas, rapidly cooling it to 200℃, avoiding the dioxin re-formation temperature range.",
344: "Finally, activated carbon powder is sprayed through the dry reaction device to adsorb dioxins. After the flue gas enters the bag filter, the unreacted activated carbon continues to adsorb harmful substances, and solid particulates and solid-phase dioxins are efficiently intercepted by the bag filter.",
345: "2.5.2 NOX Removal Process",
346: "The chemical reaction equations are as follows:",
347: "Urea  NH2CONH2+2NO+1/2O2=2N2+CO2+2H2O",
348: "Or ammonia water  4NH3+4NO+O2=4N2+6H2O",
349: "Through the above reactions, nitrogen, water and carbon dioxide are finally formed.",
350: "2.5.3 Deacidification Process",
351: "Through the dry reaction device, hydrated lime powder is sprayed into the Venturi duct to react chemically with the flue gas, achieving further deacidification. The basic chemical reaction equations are as follows:",
352: "SO3+Ca(OH)2=CaSO4+H2O SO2+Ca(OH)2=CaSO3+H2O 2HCl+Ca(OH)2= CaCl2+2H2O",
353: "2HF+Ca(OH)2=CaF2+2H2O",
354: "The hydrated lime spraying feeding device is used in the flue gas purification treatment system. The absorbent device is arranged between the quench tower and the bag filter. Through the absorbent mixer on the flue, the absorbent is evenly mixed into the flue gas and deposited on the bag walls of the bag filter, forming a filter cake, so that the deposited absorbent continues to absorb the gaseous pollutants in the flue gas.",
355: "Chapter 3 Engineering Design",
356: "Principles of Overall Scheme Design",
357: "The general layout has clear zoning and convenient management; pedestrian routes and vehicle routes are separated, transport access and exit are smooth, roads within the plant are unobstructed forming a ring route, meeting fire protection requirements; the flue gas emission of the main plant building is downwind, and offices and other living areas are upwind; full greening beautifies the environment, leaving no bare ground as far as possible.",
358: "General Layout",
359: "Project Site Planning Concepts Based on Layout and Site Selection Principles",
360: "Functional Zoning",
361: "According to the process flow, functions and wind direction, the buildings and structures in the plant are divided into three functional zones:",
362: "Office zone: including offices and parking lot. This is a relatively clean zone in the plant with high environmental requirements; it should be arranged away from various pollution sources and located on the upwind side of the prevailing wind direction.",
363: "Main production zone: including the waste storage pit, ash and slag collection area and resource recovery area. The main plant building is the main building of the plant; on the premise of meeting various protection distances, it can be close to the auxiliary production zones and the office building.",
364: "Heat supply station: including water pump house, cooling tower, water treatment device and clear water pool.",
365: "To facilitate the work of management personnel and external business contacts, the comprehensive office building is arranged near the plant gate and on the upwind side of the prevailing wind direction.",
366: "The open space between the office building and the main plant building is centrally arranged with greening as a protective isolation belt.",
367: "Main Items",
368: "Main plant building of the waste pyrolysis gasification treatment station, including the following:",
369: "1 set of 5T/D pyrolysis gasifier and its supporting equipment;",
370: "Waste transport tipping hall and pretreatment waste storage pit;",
371: "Leachate collection area;",
372: "Slag removal and ash collection area;",
373: "Control and monitoring room;",
374: "Auxiliary rooms",
375: "Office area, mainly used for office, technology, exhibition center, reception room, meetings and shift dormitories, etc.",
376: "Heat supply station, collecting pool, etc., used for heat supply to surrounding residents and enterprises/institutions, and for storing the plant-wide production and fire-fighting water.",
377: "Preliminary Design Drawings",
378: "Complete equipment with a processing capacity of 5 tons/day, ordinary layout, main plant building area approx. 800m2. Height design: waste room 12m, main equipment plant 10m, auxiliary building 3m;",
379: "Chapter 4 Project Implementation and Schedule",
380: "The project implements the owner responsibility system. The owner entrusts the design, raises construction funds, organizes the bidding and tendering of the project, complies with the relevant requirements of the contract law, and organizes construction and production. The project duration is expected to be 120 days.",
381: "4-1 Installation and Commissioning Schedule",
}
