# -*- coding: utf-8 -*-
# Batch 2: ids 118-233 (feeding/conveying, pyrolysis gasification, waste heat, flue gas start)
PART = {
118: "Feeding and Conveying System",
119: "Waste Crane",
120: "The waste grab crane is one of the key process equipment of the pyrolysis gasification plant, directly affecting the operational reliability of the plant. Its main components are imported products.",
121: "The waste grab crane is located above the waste pit and is mainly responsible for feeding, handling,",
122: "turning over, sorting and stacking of incoming waste and transferred waste. This project is equipped with 1 single-girder grab crane.",
123: "The waste grab crane mainly consists of six major parts: single girder, crane travel mechanism, hoisting mechanism, trolley travel mechanism, electrical equipment and grab. Except for the electrical equipment, the other five parts have their own motors for separate driving, meeting the pile-turning and feeding requirements of production.",
124: "The grab is of the hydraulic multi-clamshell type.",
125: "The traveling grab crane grabs the waste into the receiving hopper of the double screw conveyor, and grabs the waste in the storage pit into the receiving hopper of the high-temperature pyrolysis gasifier, where it is pushed into the furnace by the hydraulic pusher device.",
126: "2.2.4 High-Temperature Pyrolysis Gasification System",
127: "Based on the chemical characteristics of different components in the waste, this technology efficiently combines waste pyrolysis gasification with oxygen-enriched combustion through staged combustion in the furnace, and is a treatment technology developed for mixed waste.",
128: "The main body is designed as two relatively independent units: a high-temperature pyrolysis gasification zone and a gas-solid separation combustion zone. The high-temperature pyrolysis gasification zone achieves full decomposition and carbonization of the organic matter in the waste, and the gas-solid separation combustion zone achieves full combustion and rendering harmless of the combustible gas and fixed carbon, organically combining pyrolysis gasification with high-temperature combustion throughout the process.",
129: "The grate of the primary combustion chamber is divided into a drying zone, a pyrolysis zone, a main combustion zone and a burnout zone. The drying and pyrolysis zone is located under the front arch, supplied with a small amount of high-temperature air by the first air chamber. After being dried in this zone, the waste is pyrolyzed into combustible gas (CH4, CO, etc.) in a reducing atmosphere; the gas-phase products enter the secondary combustion chamber and undergo oxygen-enriched combustion under the action of the secondary high-temperature air, with the temperature controlled above 850℃ to thoroughly decompose harmful gases and dioxins. The solid-phase products are fully burned in the combustion zone; in the burnout zone the residual carbon is basically burnt out, and the small remaining amount is re-burned in this section. The burnt slag falls into the slag collection hopper and is discharged into the slag room by the slag discharger.",
130: "By regulating parameters such as the primary and secondary air velocity, air volume, temperature and feeding speed, staged combustion is performed to control the combustion conditions in the furnace and rationally distribute the release of chemical energy, so as to achieve complete burnout of the waste.",
131: "Schematic diagram of the working principle.",
132: "Grate design length 11m, width 0.8m; secondary combustion chamber space 21m3",
133: "Secondary combustion chamber outlet air volume: 5400Nm3/h; design temperature 850℃.",
134: "The burner uses natural gas or diesel fuel, with power of 1.1kw and calorific value greater than 30wkcal/h. When the furnace temperature is below 850℃, the burner starts automatically, and stops automatically after the temperature rises.",
135: "Slag discharger: combined screw + scraper with water seal. Its features are as follows:",
136: "The screw ash discharger discharges the ash and slag below the furnace body to the rear of the furnace body, closely connected with the scraper conveyor. Thanks to the water-seal structure, the scraper conveyor has perfect air tightness and can maintain the negative pressure of the furnace.",
137: "Thanks to the water seal, no dust is generated during slag discharge.",
138: "It can effectively remove the residual sewage, so that the moisture content of the slag is only 15～25%. Therefore, there is almost no",
139: "water leakage in the slag pit.",
140: "The water temperature in the slag discharger will be kept below 60℃.",
141: "2.2.5 Waste Heat Recovery System",
142: "The equipment of the waste heat utilization system mainly includes: integrated heat exchanger.",
143: "The water-cooled section uses the waste heat from waste combustion to output hot water (if there is no domestic hot water demand in the plant, it is directly cooled in circulation); while cooling the high-temperature flue gas, it maximizes the utilization of heat energy. The air-cooled section mainly uses the waste heat of the exhaust gas to heat the primary and secondary air, realizing resource recycling of waste treatment.",
144: "Structure and working principle: the equipment consists of cover plates, shell, heat exchange plates, manhole, flue gas inlet, flue gas outlet, water inlet, water outlet, exhaust port, etc. Under the action of the main fan, the flue gas side of the equipment maintains a certain negative pressure. The high-temperature flue gas enters from the flue gas inlet, flows through hundreds of partition intervals and flows out from the flue gas outlet. The cooling water pump pumps cold water in from the water inlet, which flows through the densely distributed lattice cavities and flows out from the water outlet. Since the flue gas temperature is higher than the cold water temperature, its heat is transferred to the cold water through the pipe wall, thereby lowering its own flue gas temperature and heating the water. The flue gas temperature is higher than the air temperature, so its own temperature is reduced while heating the oxygen supply air.",
145: "The new wide-channel plate heat exchanger has low turbulent flow velocity and a high heat transfer coefficient, which is 2 times that of the tubular type; the heat transfer coefficient is high, and the heat exchange area is about 1/2 of the tubular type; the structure is compact, with the heat exchange area per unit volume more than 3 times that of the tubular type, small footprint and light weight.",
146: "The intense turbulence of the fluid results in few deposits, easy cleaning and a very low fouling factor; the flow channels are smooth, with no dead corners, so dust accumulation is not easy.",
147: "2.2.6 Flue Gas Purification System",
148: "The flue gas purification system adopts the combination of \"SNCR + semi-dry quenching deacidification tower + dry reaction device + activated carbon adsorption + bag filter technology\", which can effectively remove NOx, dust, SO2, HCL, heavy metals and other pollutant components in the flue gas, so that the exhaust gas is discharged in compliance with standards.",
149: "The flue gas treatment equipment includes: SNCR denitration system, semi-dry quenching deacidification tower, dry reaction device, bag filter, induced draft fan, chimney and other equipment.",
150: "SNCR Denitration System",
151: "The SNCR denitration system performs high-temperature denitration of NOx in the flue gas at the high-temperature section in the furnace.",
152: "In the selective non-catalytic reduction (SNCR) nitrogen oxide removal process, the reducing agent is injected into the hot flue gas in the form of an aqueous solution (urea) or gas (ammonia).",
153: "Usually water is used as the driving carrier for urea solution injection. By controlling the amount of sprayed water, the injection distance of the urea solution can be effectively increased with little energy consumption, and it can also be used when necessary to lower the flue gas temperature, so that the urea reacts with the nitrogen oxides in the flue gas within the appropriate temperature range.",
154: "A CO(NH2)2 urea solution with a concentration of ~10％ is evenly stirred in the preparation tank and then sent to the urea storage tank for storage, and then boosted by the atomization pump into the nozzle. The nozzle is atomized by pressure and sprayed into the furnace. The flue gas is fully mixed with the atomized urea solution in the area below the nozzle, and the NOx components in the flue gas undergo a reduction reaction with CO(NH2)2 in the presence of O2, while the moisture of the urea solution is completely vaporized by the flue gas and carried away by it. When the ratio of CO(NH2)2 to NOx is 2:1, the NOx reduction efficiency is about 40%.",
155: "The solution preparation device is shown in the figure",
156: "The denitration system adopts automatic adjustment control. The nitrogen oxide content in the discharged flue gas and the denitration agent form a control loop, and the denitration agent is automatically adjusted according to changes in the nitrogen oxide content.",
157: "Preparation tank material 304, volume 1m³",
158: "Atomizing spray gun Q=20kg/h, gun body 316L, nozzle 316L, pump Q=0.4m3/h, H=60m",
159: "Semi-Dry Quenching Deacidification Tower",
160: "The system adopts a counter-current quench tower, and the high-temperature flue gas enters from the bottom of the quench tower. Quenching lye is sprayed into the quench tower, and the quench water is quickly atomized by compressed air. The nozzle is of the double-layer multi-orifice type, increasing the water-gas contact area and accelerating the reaction rate.",
161: "The atomized quench water directly contacts the flue gas, causing the flue gas temperature to drop rapidly. Quenching from 400℃ to 200℃ — the setting of this temperature range avoids the dioxin re-synthesis temperature range, thereby achieving the purpose of suppressing the re-generation of dioxins. During the quenching process, in addition to cooling, it also has the functions of washing, dust removal and deacidification.",
162: "The atomization of the quench water is realized by the quench pump station, which consists of an atomization pump, spray guns, piping system, air path system, temperature detection system, etc.",
163: "The quench spray gun adopts a gas-liquid two-phase nozzle, spraying fine atomized water into the flue gas. The spray gun has two inputs: one for water and the other for compressed air. To effectively protect the downstream equipment, one quench pump is in use and one on standby.",
164: "The quench tower consists of the tower shell, anti-corrosion castable and dual-fluid spray system.",
165: "The quench tower is arranged vertically, lined with an anti-corrosion and heat insulation layer. Water spraying is used for cooling, and the quench water is atomized by compressed air.",
166: "The dual-fluid atomizing nozzle has a large spray diameter and wide coverage, mixing more fully with the flue gas, which is conducive to cooling and conditioning of the flue gas. The core of the dual-fluid spray system is the nozzle. In normal operation, compressed air and water at certain pressures need to be supplied to the nozzle simultaneously. Inside the nozzle, the compressed air and water strike each other several times to produce very fine particles. When the atomized particles mix with the high-temperature flue gas, they evaporate rapidly in a short time and carry away heat. With the selected spray gun at an appropriate compressed air pressure, 90% of the particles are smaller than 150μm, ensuring 100％ evaporation of the quench water and no wet bottom (\"over-spray\").",
167: "The quench water spray volume is regulated by the regulating valve, which is interlocked with the quench tower outlet temperature and automatically adjusted to ensure that the quench tower outlet temperature does not exceed 200℃, protecting the downstream equipment. The amount of lye added is controlled by the concentration of acidic pollutants in the flue gas discharge; under normal conditions the pH value of the water in the quench water tank is controlled at 9- 10.",
168: "Specification: Φ1500*6000mm",
169: "Material: Q235B + 120mm acid and alkali resistant castable",
170: "Atomization spray volume: 300Kg/h; gun body 316L, nozzle 316L",
171: "Dry Flue Gas Treatment Device",
172: "It mainly utilizes the surface adsorption characteristics of activated carbon and the neutralization reaction capacity of hydrated lime. A dry reaction device is arranged before the bag filter; the activated carbon and hydrated lime powder are fed into the Venturi duct by a small screw conveyor through a quantitative feeding device, where the harmful substances in the flue gas are adsorbed and reacted.",
173: "When the flue gas enters the bag filter, the unreacted activated carbon and hydrated lime powder are adsorbed on the surface of the filter bags, continuing to adsorb harmful substances and react with the residual acidic gases in the flue gas.",
174: "Bag Filter",
175: "This bag filter consists of a shell, filter bags, ash hopper, ash discharge device, support and pulse cleaning system, etc. When the dust-containing gas enters the filter from the air inlet, it first hits the inclined baffle in the middle of the air inlet, and the airflow turns and flows into the ash hopper. At the same time, the airflow speed slows down, and due to gravity settling, the coarse dust particles in the gas directly fall into the ash hopper, playing a pre-dusting role. The airflow entering the ash hopper then turns upward and passes through the filter bags with internal metal frames, where the dust is captured on the outer surface of the filter bags. The purified gas enters the clean chamber at the upper part of the filter bag room and is collected into the air outlet pipe for discharge.",
176: "The key equipment of the bag filter is the filter bag material. Since the 1980s, countries have been committed to the development of filter media technology, and modern technology often uses PTFE surface filter materials in bag filters, which has greatly improved the treatment of flue gas, chemical corrosion, clogging and rupture. The membrane filter bag uses the membrane surface with a uniform fine pore size to replace the function of the primary dust cake, making the dust penetration rate nearly zero. Due to the low friction coefficient, hydrophobicity, temperature resistance and anti-aging characteristics of the membrane material, it has excellent effects; during operation, the inside of the filter material is not easily blocked, can maintain a low pressure loss, improves the service life of the filter material and reduces operating costs. PTFE membrane-coated filter material has been used in incineration plants for nearly ten years, and its effectiveness not only captures fine dust emissions at the highest efficiency, but also ensures reliable system operation. PTFE membrane-coated filter bags can filter dust particles down to 0.3 microns. Dust cleaning adopts pulse high-pressure air jetting; reasonable pulse intervals and pulse widths, as well as the good cleaning performance of the filter bags, greatly ensure that the operating resistance of the equipment remains at a stable level, not exceeding 1500Pa, and keep the flue gas treatment volume always in a stable state, so that the whole system works in a highly efficient and stable environment.",
177: "The control objects of the filter include: cleaning control, ash discharge valve control, etc.",
178: "The filter has manual and automatic conversion functions, and requires operation both from the control room (plant-wide centralized or central control room) and locally. The specific control requirements of the filter are: ① cleaning control — when the pressure difference between the inlet and outlet exceeds the set pressure, the fixed differential pressure control starts and the pulse valves are automatically actuated for cleaning; through PLC programming, intermittent pulse cleaning actions with different intervals and different cycles can be realized, and when the cleaning of all filter bags is completed, the cleaning action is automatically completed. ② Manual opening and closing of the ash discharge valve.",
179: "Electrostatic Precipitator",
180: "After the flue gas enters the high-voltage dust removal unit, under the action of the high-voltage pulse electrostatic field, the remaining oil mist and water are attached by high-density electrons or positive ions; after being charged, they migrate downward along the inner wall of the tube, and are collected and captured, producing ionization, adsorption, decomposition, carbonization and other phenomena.",
181: "On the inner wall of the tube acting as the dust collection electrode, the condensed water forms a liquid film that continuously deposits and flows downward under gravity, realizing the renewal and automatic cleaning of the electrode surface. The cleaned gas is discharged into the atmosphere by the exhaust fan at the rear of the purification device.",
182: "The wastewater collected at the bottom of the purifier tower includes condensed water, carbonized oil fume particles, and the oil-water mixture discharged by spraying.",
183: "Chimney",
184: "Carbon steel + nano coating is used for anti-corrosion, with a height of 45 meters to ensure its service life. The chimney design is strictly implemented in accordance with the Standard for Pollution Control on Municipal Solid Waste Incineration (GB18485-2014), and conforms to the operating conditions of the complete equipment. In accordance with the Determination of Particulates and Sampling Methods for Gaseous Pollutants Emitted from Stationary Pollution Sources (GB/T16157-1996), permanent sampling holes are provided, and facilities for sampling and measurement are installed, for use at ~150℃.",
185: "Attached: test platform, flue gas analyzer port, drainage port, lightning protection grounding, etc.",
186: "2.2.7 Three-Waste (Bottom Ash, Fly Ash, Leachate) Treatment System",
187: "Bottom ash collection and disposal: the ash and slag under the grate fall periodically and automatically, and are discharged into the slag collection hopper via the screw conveyor; the burnt slag falls directly from the tail of the grate into the ash collection hopper, and is discharged directly to the slag room by the water-seal scraper slag discharger. According to test results it is determined to contain no toxic or harmful substances, belonging to non-hazardous waste, and can be sent to brick plants as raw material for comprehensive utilization or safely landfilled;",
188: "Fly ash collection and disposal: fly ash is hazardous waste and should undergo permanent solidification treatment. Treatment methods include the cement solidification method, melting solidification method, chemical agent method, etc. Currently the more commonly used is the \"cement + chelating agent\" stabilization treatment process, in which fly ash, cement, water and chelating agent are mixed in certain proportions. This method is simple and reliable in process and saves investment.",
189: "A semi-automatic solidification device can be added on site, or the fly ash can be sent directly to a qualified unit for disposal.",
190: "Leachate recovery and treatment system: on the side of the waste pit near the discharge doors, a continuous leachate collection trough is arranged along the entire length, covered with precast slabs on the upper part to isolate the waste. The leachate is collected through the trench into the leachate collection well.",
191: "The moisture content of the waste in this project is extremely low; the small amount of leachate can be directly re-sprayed into the furnace for high-temperature harmless disposal.",
192: "2.2.8 Central Control System",
193: "The design scope of the control system of this project mainly includes: the waste transport and receiving system, conveying system, pyrolysis gasification system, flue gas purification system, flue air system, steam-water system, thermal system, fuel oil system, plant power system, compressed air system, ash and slag system, etc.",
194: "In addition to the above systems, it also includes the industrial television monitoring system.",
195: "This project uses a PLC control system including electrical control cabinets, industrial controllers and other devices. The PLC program automatically adjusts the start/stop and variable-frequency speed regulation of motors to achieve stable control of the combustion temperature, oxygen supply, feed weight and time. The operating conditions and related process parameters of the whole system can be displayed on the computer screen for timely control. The control cabinet has two control modes: interlocked and individual. Alarms are provided for equipment faults, air supply pressure, etc., and fault signals are sent to the central control room. \"Interlocked\" operation: through the PLC, each electric actuator can be interlock-controlled or manually controlled individually; \"individual\" operation: the PLC cabinet can operate independently in \"manual\" or \"automatic\" mode.",
196: "2.3 Equipment List",
197: "5T/D Complete Waste Pyrolysis Gasification Treatment Plant",
198: "No.",
199: "Equipment No.",
200: "Item",
201: "Name",
202: "Specifications\t&\tTechnical\tData\t-\t-",
203: "Data",
204: "Qty",
205: "I",
206: "Feeding System",
207: "ZT-1-1",
208: "Feed hopper",
209: "ZT-1-2",
210: "Traveling grab crane",
211: "ZT-1-3",
212: "Hydraulic pusher system",
213: "II",
214: "Pyrolysis Gasification System",
215: "ZT-2-1",
216: "Chain grate pyrolysis gasifier (including",
217: "secondary combustion chamber)",
218: "Processing capacity 5 tons/day, flue gas outlet temperature above 900℃",
219: "ZT-2-2",
220: "Thermal insulation",
221: "ZT-2-3",
222: "Blower",
223: "Air volume: 3000Nm3/h\tAir pressure: 4500pa",
224: "5.5KW",
225: "ZT-2-4",
226: "Combustion-support system (including burner,",
227: "oil tank)",
228: "Ignition burner 0.75kw, auxiliary burner 2.6",
229: "pump 0.37, with storage tank",
230: "ZT-2-5",
231: "Slag removal system",
232: "7.5Kw",
233: "III",
}
